server:
  port: 8997

spring:
  application:
    name: raysvivi-blog
  ssl:
    key-alias: tomcat
    key-store-password: llvbmcn9    #填写pfx-password.txt文件内的密码。
    key-store-type: PKCS12
    key-store: classpath:8931588_www.raysvivi.com.pfx    #您需要使用实际的证书名称替换domain_name.pfx。
  datasource:
    #配置hikari连接池
    hikari:
      minimum-idle: 4
      maximum-pool-size: 16
      connection-timeout: 10000
      idle-timeout: 30000
      connection-init-sql: set names utf8mb4
    dynamic:
      primary: readDB
      datasource:
        readDB:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.122.19.56:3306/raysvivi?characterEncoding=UTF-8&useSSL=false
          username: root
          password: Ray/1990
        writeDB:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.122.19.56:3306/raysvivi?characterEncoding=UTF-8&useSSL=false
          username: root
          password: Ray/1990

mybatis-plus:
  executor-type: simple
  mapper-location: mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tJqiBm1YrQ8GotYJUiC
    accessKeySecret: hqt7C9nbpY9CeGW6RfMmiWVbjBQvdf
    bucketName: persional-images
